app = "equinoid-redis"
primary_region = "gru"

[build]
  image = "redis:7-alpine"

[[services]]
  protocol = "tcp"
  internal_port = 6379
  
  [[services.ports]]
    port = 6379

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "redis_data"
  destination = "/data"
